modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Village%20Bell%20Recipe"
logoFile="icon.png"

[[mods]]
modId="villagebellrecipe"
version="3.5"
displayName="Village Bell Recipe"
displayURL="https://serilum.com/mod/village-bell-recipe"
authors="Rick South"
description='''Adds a recipe for the village bell item.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, BirdieMiner, Cherriesaurus, Jeremy Langford, Michael W. S., Shana Gitnick, Sukhmai, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.villagebellrecipe]]
    modId="collective"
    type="required"
    versionRange="[7.62,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.villagebellrecipe]]
    modId="minecraft"
    type="required"
    versionRange="[1.21]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "villagebellrecipe.mixins.json"